---
title: 'gmean na.rm=TRUE is much slower than na.rm=FALSE #4849'
output: html_document
date: "2024-02-15"
---

gmean na.rm=TRUE is much slower than na.rm=FALSE #4849
library(data.table) ## 1.13.5
setDTthreads(0L) ## 40
set.seed(108)
N = 1e9L
K = 1e2L
DT = list()
DT[["id3"]] = factor(sample(sprintf("id%010d",1:(N/K)), N, TRUE))
DT[["v3"]] =  round(runif(N,max=100),6)
setDT(DT)


```{r}

library(atime)
library(ggplot2)
library(data.table)
library(directlabels)

```

```{r}
  tdir <- tempfile()
  dir.create(tdir)
  git2r::clone("https://github.com/Rdatatable/data.table", tdir)
  
```




system.time(nat <- DT[, .(v3=mean(v3, na.rm=TRUE)), by=id3, verbose=TRUE])
```{r,warning=FALSE,message=FALSE}
atime.list.4849 <- atime::atime_versions(
  pkg.path=tdir,
  pkg.edit.fun=function(old.Package, new.Package, sha, new.pkg.path){
    pkg_find_replace <- function(glob, FIND, REPLACE){
      atime::glob_find_replace(file.path(new.pkg.path, glob), FIND, REPLACE)
    }
    Package_regex <- gsub(".", "_?", old.Package, fixed=TRUE)
    Package_ <- gsub(".", "_", old.Package, fixed=TRUE)
    new.Package_ <- paste0(Package_, "_", sha)
    pkg_find_replace(
      "DESCRIPTION", 
      paste0("Package:\\s+", old.Package),
      paste("Package:", new.Package))
    pkg_find_replace(
      file.path("src","Makevars.*in"),
      Package_regex,
      new.Package_)
    pkg_find_replace(
      file.path("R", "onLoad.R"),
      Package_regex,
      new.Package_)
    pkg_find_replace(
      file.path("R", "onLoad.R"),
      sprintf('packageVersion\\("%s"\\)', old.Package),
      sprintf('packageVersion\\("%s"\\)', new.Package))
    pkg_find_replace(
      file.path("src", "init.c"),
      paste0("R_init_", Package_regex),
      paste0("R_init_", gsub("[.]", "_", new.Package_)))
    pkg_find_replace(
      "NAMESPACE",
      sprintf('useDynLib\\("?%s"?', Package_regex),
      paste0('useDynLib(', new.Package_))
  },
  seconds.limit=1,
  N=10^seq(1,9),
  setup={
    K = 10^seq(1,2)
    DT = list()
    DT[["id3"]] = factor(sample(sprintf("id%010d",1:(N/K)), N, TRUE))
    DT[["v3"]] =  round(runif(N,max=100),6)
    setDT(DT)
  },
  expr= data.table:::`[.data.table`(DT,, .(v3=mean(v3)), by=id3, verbose=TRUE),
  "Before"="616dfc5093b0f7eea6aafbc1ecc744a541088b12",#https://github.com/Rdatatable/data.table/tree/616dfc5093b0f7eea6aafbc1ecc744a541088b12
  "Regression"="3ca0dbfb26c59b047acd6b0c5b400b6222ad6f6b",#https://github.com/Rdatatable/data.table/pull/4851/commits/3ca0dbfb26c59b047acd6b0c5b400b6222ad6f6b
  "fixed"="3bfe51ec74e26045836abd9c2e16144beeba8761")#https://github.com/Rdatatable/data.table/commit/3bfe51ec74e26045836abd9c2e16144beeba8761
```


```{r}
png()
plot(atime.list.4849)+
  labs(title = "gmean na.rm=TRUE is much slower than na.rm=FALSE #4849")

png("atime.list.4849.png")
plot(atime.list.4849)+
  labs(title = "gmean na.rm=TRUE is much slower than na.rm=FALSE #4849")
dev.off()
```

