---
title: 'Topn doing order |> head/tail #5167'
output: html_document
date: "2024-01-11"
---

Not Regression
setDTthreads(1L)
x = seq.int(1e8)
b <- function() {
  bench::mark(
    topn(x,n,decreasing=TRUE),
    kit::topn(x,n,decreasing=TRUE),
    data.table:::forder(x,decreasing=TRUE)[1:n]
  )
}
library(data.table)
setDTthreads(1L)
x = as.double(seq.int(1e7))
b <- function() {
  bench::mark(
    topn(x,n,decreasing=FALSE),
    data.table:::forder(x,decreasing=FALSE)[1:n]
  )
}
x = as.double(seq.int(1e7))

```{r}

PR.5167 <- atime::atime(
  N =unique(as.integer(1:1e9)),
  setup = {
    x = as.double(N)
  },
  seconds.limit = 0.1,
  topn = topn(x,N,decreasing=FALSE),
  forder = data.table:::forder(x,decreasing=FALSE)[1:N]
  
  
)
```


```{r,warning=FALSE}
library(data.table)
library(atime)
library(kit)

```


```{r}
tdir <- tempfile()
dir.create(tdir)
git2r::clone("https://github.com/Rdatatable/data.table", tdir)
  
```


```{r,warning=FALSE}

atime.list.5167 <- atime::atime_versions(
  pkg.path=tdir,
  pkg.edit.fun=function(old.Package, new.Package, sha, new.pkg.path){
    pkg_find_replace <- function(glob, FIND, REPLACE){
      atime::glob_find_replace(file.path(new.pkg.path, glob), FIND, REPLACE)
    }
    Package_regex <- gsub(".", "_?", old.Package, fixed=TRUE)
    Package_ <- gsub(".", "_", old.Package, fixed=TRUE)
    new.Package_ <- paste0(Package_, "_", sha)
    pkg_find_replace(
      "DESCRIPTION", 
      paste0("Package:\\s+", old.Package),
      paste("Package:", new.Package))
    pkg_find_replace(
      file.path("src","Makevars.*in"),
      Package_regex,
      new.Package_)
    pkg_find_replace(
      file.path("R", "onLoad.R"),
      Package_regex,
      new.Package_)
    pkg_find_replace(
      file.path("R", "onLoad.R"),
      sprintf('packageVersion\\("%s"\\)', old.Package),
      sprintf('packageVersion\\("%s"\\)', new.Package))
    pkg_find_replace(
      file.path("src", "init.c"),
      paste0("R_init_", Package_regex),
      paste0("R_init_", gsub("[.]", "_", new.Package_)))
    pkg_find_replace(
      "NAMESPACE",
      sprintf('useDynLib\\("?%s"?', Package_regex),
      paste0('useDynLib(', new.Package_))
  },
  N=10^seq(1,7),
  setup={
    setDTthreads(1L)
    set.seed(373)
    x = seq.int(N)
    },
  expr=data.table:::forder(x,decreasing=TRUE, 1:N ),
                                           
  "Before"="",
  "Regression"="13caa28dd41621bedb4720e29acda660416465b8") #
  #"Fixed"="ba32f3cba38ec270587e395f6e6c26a80be36be6")#
```



```{r}
library(ggplot2)


png()
plot(atime.list.5167)+
  labs(title = "Topn doing order |> head/tail #5167")

png("atime.list.5167.png")
plot(atime.list.5167)+
  labs(title = "Topn doing order |> head/tail #5167")
dev.off()
```

