---
title: "j=list(var) slower than j=var, with by= #7122"
author: "Doris Amoakohene"
date: "2024-03-14"
output: html_document
---


```{r}
require(data.table) ## 1.9.3
DT <- data.table(x=rep(1:1e7, 2L), y=1L)
system.time(ans1 <- DT[, .N, by=x])            ## 3.5 sec
system.time(ans2 <- DT[, list(N = .N), by=x])  ## 5.8 sec

#Similar cases:

dd <- data.table(x=1:1e7,key="x")
system.time(de <- dd[dd,1,by=.EACHI])       ## 2.1 sec
system.time(df <- dd[dd,list(1),by=.EACHI]) ## 3.8
system.time(dg <- dd[dd,x,by=.EACHI])       ## 2.3
system.time(dh <- dd[dd,list(x),by=.EACHI]) ## 4.8
```


```{r}

library(atime)
library(ggplot2)
library(data.table)

```


```{r}
result.withby <- atime::atime(
  N =unique(as.integer(1:1e9)),
  setup = {
    DT <- data.table(x=rep(N, 2L), y=1L)
    dd <- data.table(x=N,key="x")
  },
  seconds.limit = 0.001,
  
    ans1 = DT[, .N, by=x],
    ans2 = DT[, list(N = .N), by=x],
    de = dd[dd,1,by=.EACHI],
    df =  dd[dd,list(1),by=.EACHI],
    dg = dd[dd,x,by=.EACHI],
    dh = dd[dd,list(x),by=.EACHI]
  
)
```

require(data.table) ## 1.9.3
DT <- data.table(x=rep(1:1e7, 2L), y=1L)
system.time(ans1 <- DT[, .N, by=x])            ## 3.5 sec
system.time(ans2 <- DT[, list(N = .N), by=x])  ## 5.8 sec
Similar cases:

dd <- data.table(x=1:1e7,key="x")
system.time(de <- dd[dd,1,by=.EACHI])       ## 2.1 sec
system.time(df <- dd[dd,list(1),by=.EACHI]) ## 3.8
system.time(dg <- dd[dd,x,by=.EACHI])       ## 2.3
system.time(dh <- dd[dd,list(x),by=.EACHI]) ## 4.8
```{r}
plot(result.withby)+
  labs(title = "j=list(var) slower than j=var, with by= #7122")

png("result.withby.png")
plot(result.withby)+
  labs(title = "j=list(var) slower than j=var, with by= #7122")
dev.off()
```


```{r}
result.712 <- atime::atime(
  N =unique(as.integer(1:1e9)),
  setup = {
    
    dd <- data.table(x=N,key="x")
  },
  seconds.limit = 0.001,
  
  de = dd[dd,1,by=.EACHI],
  df =  dd[dd,list(1),by=.EACHI],
  dg = dd[dd,x,by=.EACHI],
  dh = dd[dd,list(x),by=.EACHI]
  
)
```


```{r}
plot(result.712)+
  labs(title = "j=list(var) slower than j=var, with by= #7122")

png("result.712.png")
plot(result.712)+
  labs(title = "j=list(var) slower than j=var, with by= #7122")
dev.off()
```
